blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/TishinaVC/W11Hammer/discussions
    about: Please use Discussions for questions and general chat
